'use strict';

const SUPABASE_URL='https://ifanefgaiuzkbjtttiqn.supabase.co';
const SUPABASE_KEY='sb_publishable_LYSS9b_Yxn29-fM0UK_mIg_Bot-M61k';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const state={session:null,profile:null,company:null,page:'dashboard',data:{},search:'',requestOnly:false,isPlatformAdmin:false};

const roleMenus={
  SALES:[['dashboard','⌂','หน้าหลัก'],['orders','▤','Orders'],['customers','♙','ลูกค้า'],['delivery','⌖','ติดตามการส่ง']],
  WAREHOUSE:[['dashboard','⌂','หน้าหลัก'],['warehouse','▣','งานคลัง'],['stock','▦','Stock'],['counts','✓','ตรวจนับ Stock'],['transfers','⇄','โอนคลัง']],
  LOGISTICS:[['dashboard','⌂','หน้าหลัก'],['delivery','⌖','ขนส่ง / POD'],['orders','▤','Orders'],['stock','▦','Stock']],
  OWNER:[['dashboard','⌂','Executive Dashboard'],['profit','◫','Sales & Profit'],['stock','▦','Stock Health'],['delivery','⌖','Delivery Performance'],['audit','≡','Audit Log']],
  ADMIN:[['dashboard','⌂','หน้าหลัก'],['orders','▤','Orders'],['warehouse','▣','งานคลัง'],['stock','▦','Stock'],['counts','✓','ตรวจนับ Stock'],['transfers','⇄','โอนคลัง'],['delivery','⌖','ขนส่ง / POD'],['profit','◫','Profit'],['masters','⚙','Master Data'],['users','♟','Users / Roles'],['settings','⚒','ตั้งค่าระบบ'],['audit','≡','Audit Log']]
};
const roleThai={SALES:'ฝ่ายขาย',WAREHOUSE:'คลังสินค้า',LOGISTICS:'ขนส่ง',OWNER:'ผู้บริหาร',ADMIN:'ผู้ดูแลระบบ'};
const statusThai={DRAFT:'ร่าง',CONFIRMED:'รอจัดสินค้า',PARTIAL_ISSUE:'จ่ายบางส่วน',WAITING_LOGISTICS:'รอจัดรถ',IN_DELIVERY:'กำลังส่ง',DELIVERED:'ส่งสำเร็จ',CANCELLED:'ยกเลิก',PLANNED:'วางแผน',COMPLETED:'สำเร็จ',IN_TRANSIT:'อยู่ระหว่างโอน',POSTED:'บันทึกแล้ว',FINAL:'Final',ESTIMATED:'Estimated',ACTIVE:'ใช้งาน',TRIAL:'ทดลองใช้',DEMO:'Demo',SUSPENDED:'ระงับ',EXPIRED:'หมดอายุ',INACTIVE:'ปิดใช้งาน'};
const nf=new Intl.NumberFormat('th-TH',{maximumFractionDigits:2});
const money=n=>'฿'+nf.format(Number(n||0));
const qty=n=>nf.format(Number(n||0));
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const dmy=v=>{if(!v)return'-';const d=new Date(v);return Number.isNaN(d.valueOf())?esc(v):new Intl.DateTimeFormat('th-TH-u-ca-gregory',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d)};
const localInput=(offset=0)=>{const d=new Date(Date.now()+offset);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)};
const requestId=p=>`${p}-${crypto.randomUUID()}`;
const can=(...roles)=>roles.includes(state.profile?.app_role);

function setLoading(on){$('#loading').classList.toggle('hidden',!on)}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.classList.toggle('error-toast',error);el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2800)}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden');setTimeout(()=>$('#modalBody input, #modalBody select')?.focus(),30)}
function closeModal(){if($('#modalBody').dataset.busy==='1')return;$('#modal').classList.add('hidden');$('#modalBody').innerHTML=''}
function fail(e){console.error(e);toast(errorText(e),true)}
function errorText(e){const m=e?.message||String(e||'เกิดข้อผิดพลาด');const map={AUTH_REQUIRED:'กรุณาเข้าสู่ระบบ',ROLE_NOT_ALLOWED:'บัญชีนี้ไม่มีสิทธิ์ทำรายการ',PLATFORM_ADMIN_REQUIRED:'บัญชีนี้ไม่มีสิทธิ์จัดการลูกค้า',COMPANY_INACTIVE:'บริษัทถูกระงับหรือหมดอายุ กรุณาติดต่อผู้ดูแล FlowStock',COMPANY_NOT_FOUND:'ไม่พบรหัสบริษัท หรือบริษัทยังไม่เปิดใช้งาน',COMPANY_CODE_EXISTS:'รหัสบริษัทนี้ถูกใช้แล้ว',COMPANY_CODE_REQUIRED:'กรุณาระบุรหัสบริษัท',ACCESS_REQUEST_ALREADY_PENDING:'บัญชีนี้มีคำขอของบริษัทอื่นที่กำลังรออนุมัติ',INVALID_OR_EXPIRED_ONBOARDING_CODE:'รหัสเปิดบริษัทไม่ถูกต้อง หมดอายุ หรือถูกใช้แล้ว',USER_LIMIT_REACHED:'จำนวนผู้ใช้ถึงขีดจำกัดแพ็กเกจแล้ว',INVALID_POD_FILE:'รองรับ POD แบบ PDF, JPG หรือ PNG ขนาดไม่เกิน 10 MB',POD_OBJECT_NOT_FOUND:'ไม่พบไฟล์ POD ที่อัปโหลด',INVALID_CUSTOMER:'ไม่พบลูกค้า',INVALID_PRODUCT:'ไม่พบสินค้า',INVALID_WAREHOUSE:'ไม่พบคลัง',INSUFFICIENT_STOCK:'Stock ไม่เพียงพอ',ORDER_NOT_ISSUABLE:'Order นี้ไม่อยู่ในสถานะที่จ่ายสินค้าได้',ORDER_NOT_READY_FOR_DELIVERY:'Order ยังจ่ายสินค้าไม่ครบ',VEHICLE_TIME_CONFLICT:'รถคันนี้มีงานซ้อนในช่วงเวลาที่เลือก',VARIANCE_REASON_REQUIRED:'กรุณาระบุเหตุผลส่วนต่าง',DELIVERY_VARIANCE_REASON_REQUIRED:'กรุณาระบุเหตุผลที่ลูกค้ารับไม่ครบ'};return map[m]||m}
function badge(s){const c=['DELIVERED','COMPLETED','POSTED','FINAL','ACTIVE'].includes(s)?'ok':['CONFIRMED','PARTIAL_ISSUE','ESTIMATED','IN_TRANSIT','TRIAL','DEMO'].includes(s)?'warn':['WAITING_LOGISTICS','IN_DELIVERY','PLANNED'].includes(s)?'blue':['CANCELLED','SUSPENDED','EXPIRED','INACTIVE'].includes(s)?'danger':'';return `<span class="badge ${c}">${esc(statusThai[s]||s||'-')}</span>`}
function empty(text='ไม่พบข้อมูล'){return `<div class="empty">${esc(text)}</div>`}
function head(title,sub='',actions=''){return `<div class="page-head"><div><h1>${esc(title)}</h1><p>${esc(sub)}</p></div><div class="actions">${actions}</div></div>`}
function cards(items){return `<div class="cards">${items.map(x=>`<div class="card"><div class="label">${esc(x[0])}</div><div class="value">${x[1]}</div><div class="hint">${esc(x[2]||'')}</div></div>`).join('')}</div>`}
function table(headers,rows){if(!rows.length)return empty();return `<div class="table-wrap"><table><thead><tr>${headers.map((h,i)=>`<th class="sortable" data-col="${i}">${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
function wireSort(){ $$('#page th.sortable').forEach(th=>th.onclick=()=>{const body=th.closest('table').tBodies[0],i=+th.dataset.col,asc=th.dataset.asc!=='1';[...body.rows].sort((a,b)=>{const x=a.cells[i]?.dataset.sort??a.cells[i]?.innerText??'',y=b.cells[i]?.dataset.sort??b.cells[i]?.innerText??'';return (Number.isFinite(+x)&&Number.isFinite(+y)?+x-+y:String(x).localeCompare(String(y),'th'))*(asc?1:-1)}).forEach(r=>body.appendChild(r));th.dataset.asc=asc?'1':'0'})}

async function init(){
  bindShell();
  const {data:{session}}=await db.auth.getSession();
  if(session)await startApp(session);else showLogin();
  db.auth.onAuthStateChange(async(event,session)=>{if(event==='SIGNED_OUT')showLogin();if(event==='SIGNED_IN'&&session&&!state.session)await startApp(session);if(event==='PASSWORD_RECOVERY')passwordRecoveryModal()});
}
function bindShell(){
  $('#loginForm').addEventListener('submit',login);$('#signupForm').addEventListener('submit',signup);$('#logoutBtn').onclick=()=>db.auth.signOut();
  $('#forgotBtn').onclick=forgotPassword;
  $('#signupBtn').onclick=()=>toggleSignup(true);$('#backLoginBtn').onclick=()=>toggleSignup(false);$('#pendingLogoutBtn').onclick=()=>db.auth.signOut();
  $('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#modalClose').onclick=closeModal;
  $('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
  $('#refreshBtn').onclick=async()=>{await loadData();render();toast('อัปเดตข้อมูลแล้ว')};
  document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
}
function toggleSignup(on){$('#loginForm').classList.toggle('hidden',on);$('#signupBtn').classList.toggle('hidden',on);$('#signupForm').classList.toggle('hidden',!on);$('#pendingView').classList.add('hidden');$('#signupError').textContent=''}
async function login(e){e.preventDefault();$('#loginError').textContent='';setLoading(true);const {error}=await db.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});setLoading(false);if(error)$('#loginError').textContent='อีเมลหรือรหัสผ่านไม่ถูกต้อง'}
async function submitAccess(){const onboarding=$('#signupOnboarding').value.trim();if(onboarding)return db.rpc('claim_tenant_admin',{p_onboarding_code:onboarding,p_full_name:$('#signupName').value.trim(),p_employee_code:$('#signupEmployee').value.trim()||null});return db.rpc('request_access',{p_full_name:$('#signupName').value.trim(),p_employee_code:$('#signupEmployee').value.trim(),p_requested_role:$('#signupRole').value,p_company_code:$('#signupCompany').value.trim()})}
async function signup(e){e.preventDefault();$('#signupError').textContent='';setLoading(true);if(state.requestOnly){const {data,error}=await submitAccess();setLoading(false);if(error)return $('#signupError').textContent=errorText(error);if(data?.status==='ACTIVE')return location.reload();showPending();return}const email=$('#signupEmail').value.trim(),password=$('#signupPassword').value;const {data,error}=await db.auth.signUp({email,password});if(error){setLoading(false);$('#signupError').textContent=errorText(error);return}if(data.session){const {data:access,error:re}=await submitAccess();if(re){setLoading(false);$('#signupError').textContent=errorText(re);return}if(access?.status==='ACTIVE')return location.reload();showPending()}else{$('#signupError').textContent='กรุณายืนยันอีเมล แล้ว Login จากนั้นกรอกข้อมูลบริษัทอีกครั้ง'}setLoading(false)}
function showLogin(){state.session=null;state.profile=null;state.company=null;state.isPlatformAdmin=false;state.requestOnly=false;state.page='dashboard';setLoading(false);$('#signupPassword').closest('label').classList.remove('hidden');$('#signupEmail').closest('label').classList.remove('hidden');$('#signupForm button[type="submit"]').textContent='ส่งคำขอเปิดใช้งาน';$('#shell').classList.add('hidden');$('#authView').classList.remove('hidden');toggleSignup(false)}
function showPending(){setLoading(false);$('#shell').classList.add('hidden');$('#authView').classList.remove('hidden');$('#loginForm').classList.add('hidden');$('#signupForm').classList.add('hidden');$('#signupBtn').classList.add('hidden');$('#pendingView').classList.remove('hidden')}
async function startApp(session){
  setLoading(true);state.session=session;
  const {data,error}=await db.rpc('get_my_context');
  if(error){throw error}
  if(!data){const {data:req}=await db.from('access_requests').select('status').eq('user_id',session.user.id).eq('status','PENDING').maybeSingle();if(req){showPending();return}state.requestOnly=true;toggleSignup(true);$('#signupEmail').value=session.user.email||'';$('#signupEmail').closest('label').classList.add('hidden');$('#signupPassword').closest('label').classList.add('hidden');$('#signupForm button[type="submit"]').textContent='ส่งคำขอเปิดใช้งาน';setLoading(false);return}
  if(!data.active){showPending();return}
  state.profile=data;state.company=data.company;state.isPlatformAdmin=Boolean(data.is_platform_admin);$('#companyName').textContent=data.company?.name||'FlowStock';$('#roleName').textContent=roleThai[data.app_role]||data.app_role;$('#sideUser').textContent=`${data.full_name} • ${data.employee_code||''}`;
  if(!data.active||!data.company?.active||['SUSPENDED','EXPIRED'].includes(data.company?.subscription_status)||(data.company?.subscription_status==='TRIAL'&&data.company.trial_ends_at&&new Date(data.company.trial_ends_at)<=new Date())){state.page='inactive';renderNav();$('#authView').classList.add('hidden');$('#shell').classList.remove('hidden');setLoading(false);render();return}
  renderNav();await loadData();$('#authView').classList.add('hidden');$('#shell').classList.remove('hidden');setLoading(false);render();
}
function renderNav(){const menus=state.page==='inactive'?[]:[...(roleMenus[state.profile.app_role]||roleMenus.SALES)];if(state.isPlatformAdmin)menus.push(['commercial','◆','Commercial Control']);$('#nav').innerHTML=menus.map(m=>`<button class="nav-btn ${state.page===m[0]?'active':''}" data-page="${m[0]}"><span class="nav-icon">${m[1]}</span>${m[2]}</button>`).join('');$$('.nav-btn').forEach(b=>b.onclick=()=>go(b.dataset.page))}
function go(page){state.page=page;state.search='';renderNav();$('#sidebar').classList.remove('open');render()}

async function loadData(){
  setLoading(true);
  const queries={
    customers:db.from('customers').select('*').order('code'),products:db.from('products').select('*').order('code'),warehouses:db.from('warehouses').select('*').order('code'),suppliers:db.from('suppliers').select('*').order('code'),vehicles:db.from('vehicles').select('*').order('code'),drivers:db.from('drivers').select('*').order('code'),
    balances:db.from('stock_balances').select('*'),movements:db.from('stock_movements').select('*').order('created_at',{ascending:false}).limit(300),
    orders:db.from('orders').select('*').order('created_at',{ascending:false}),orderLines:db.from('order_lines').select('*'),
    receipts:db.from('goods_receipts').select('*').order('receipt_date',{ascending:false}),transfers:db.from('transfers').select('*').order('transfer_no',{ascending:false}),transferLines:db.from('transfer_lines').select('*'),
    trips:db.from('delivery_trips').select('*').order('planned_start',{ascending:false}),tripLines:db.from('delivery_trip_lines').select('*'),deliveryDocs:db.from('delivery_documents').select('*').order('created_at',{ascending:false}),invoices:db.from('invoices').select('*').order('invoice_date',{ascending:false}),
    costs:db.from('monthly_product_costs').select('*').order('cost_month',{ascending:false}),counts:db.from('stock_counts').select('*').order('snapshot_at',{ascending:false}),countLines:db.from('stock_count_lines').select('*'),periods:db.from('period_closes').select('*').order('period_month',{ascending:false}),settings:db.from('app_settings').select('*'),accessRequests:db.from('access_requests').select('*').order('requested_at',{ascending:false}),users:can('ADMIN')?db.rpc('admin_list_users'):Promise.resolve({data:[],error:null}),audit:db.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(200),tenants:state.isPlatformAdmin?db.rpc('platform_list_companies'):Promise.resolve({data:[],error:null})
  };
  const entries=Object.entries(queries),results=await Promise.all(entries.map(x=>x[1]));
  results.forEach((r,i)=>{if(r.error){if(['audit','accessRequests'].includes(entries[i][0])&&!can('ADMIN','OWNER'))state.data[entries[i][0]]=[];else throw r.error}else state.data[entries[i][0]]=r.data||[]});
  setLoading(false);
}

function render(){
  const pages={dashboard:dashboardPage,orders:ordersPage,warehouse:warehousePage,stock:stockPage,counts:countsPage,transfers:transfersPage,delivery:deliveryPage,profit:profitPage,customers:customersPage,masters:mastersPage,users:usersPage,settings:settingsPage,audit:auditPage,commercial:commercialPage,inactive:inactivePage};
  $('#page').innerHTML=(pages[state.page]||dashboardPage)();wireSort();wirePage();
}
function wirePage(){
  $$('[data-action]').forEach(b=>b.onclick=()=>actions[b.dataset.action]?.(b.dataset.id));
  const search=$('#pageSearch');if(search){search.value=state.search;search.oninput=()=>{state.search=search.value.toLowerCase();render()}}
}
const byId=(list,id)=>state.data[list]?.find(x=>x.id===id);
const customerName=id=>byId('customers',id)?.name||'-';const product=id=>byId('products',id)||{};const warehouse=id=>byId('warehouses',id)||{};
const orderLines=id=>state.data.orderLines.filter(x=>x.order_id===id);const tripLines=id=>state.data.tripLines.filter(x=>x.trip_id===id);const transferLine=id=>state.data.transferLines.find(x=>x.transfer_id===id);
const stockAvailable=(pid,wid)=>{const b=state.data.balances.find(x=>x.product_id===pid&&x.warehouse_id===wid);return Number(b?.on_hand||0)-Number(b?.allocated||0)};

function dashboardPage(){
  const revenue=state.data.invoices.reduce((s,x)=>s+Number(x.revenue||0),0),gp=state.data.invoices.reduce((s,x)=>s+Number(x.revenue||0)-Number(x.product_cost||0)-Number(x.freight_cost||0)-Number(x.other_cost||0),0),open=state.data.orders.filter(x=>!['DELIVERED','CANCELLED'].includes(x.status)).length,stock=state.data.balances.reduce((s,x)=>s+Number(x.on_hand||0),0);
  const recent=state.data.orders.slice(0,8).map(o=>`<tr><td><b>${esc(o.order_no)}</b></td><td>${esc(customerName(o.customer_id))}</td><td>${dmy(o.order_date)}</td><td>${badge(o.status)}</td><td class="num" data-sort="${orderLines(o.id).reduce((s,l)=>s+Number(l.qty),0)}">${qty(orderLines(o.id).reduce((s,l)=>s+Number(l.qty),0))}</td></tr>`);
  return head(can('OWNER')?'Executive Dashboard':'ภาพรวมวันนี้','ข้อมูลจริงจากฐานข้อมูล FlowStock')+cards([['Sales',money(revenue),'Invoice ทั้งหมด'],['Gross Profit',money(gp),revenue?`GP ${(gp/revenue*100).toFixed(2)}%`:'' ],['Open Orders',nf.format(open),'รายการที่ยังไม่ปิด'],['Stock On Hand',qty(stock),'ทุกคลัง']])+`<div class="panel"><h3>Orders ล่าสุด</h3>${table(['Order','ลูกค้า','วันที่','สถานะ','จำนวน'],recent)}</div>`;
}
function ordersPage(){
  const q=state.search,rows=state.data.orders.filter(o=>`${o.order_no} ${customerName(o.customer_id)} ${o.status}`.toLowerCase().includes(q)).map(o=>{const ls=orderLines(o.id),amount=ls.reduce((s,l)=>s+Number(l.qty)*Number(l.unit_price),0);return `<tr><td><b>${esc(o.order_no)}</b></td><td>${esc(customerName(o.customer_id))}</td><td>${dmy(o.order_date)}</td><td>${badge(o.status)}</td><td class="num" data-sort="${amount}">${money(amount)}</td><td><button class="btn small-btn" data-action="viewOrder" data-id="${o.id}">เปิด</button></td></tr>`});
  return head('Orders','สร้างและติดตามคำสั่งขาย',`${can('SALES','ADMIN')?'<button class="btn primary" data-action="newOrder">+ สร้าง Order</button>':''}<button class="btn" data-action="exportOrders">ดาวน์โหลด CSV</button>`)+`<div class="toolbar"><input id="pageSearch" placeholder="ค้นหา Order / ลูกค้า / สถานะ"></div><div class="panel">${table(['Order','ลูกค้า','วันที่','สถานะ','มูลค่า',''],rows)}</div>`;
}
function customersPage(){const rows=state.data.customers.filter(x=>`${x.code} ${x.name} ${x.region}`.toLowerCase().includes(state.search)).map(x=>`<tr><td><b>${esc(x.code)}</b></td><td>${esc(x.name)}</td><td>${esc(x.region||'-')}</td><td>${x.active?badge('ACTIVE'):badge('INACTIVE')}</td></tr>`);return head('ลูกค้า','ข้อมูลลูกค้าในบริษัท')+`<div class="toolbar"><input id="pageSearch" placeholder="ค้นหาลูกค้า"></div><div class="panel">${table(['รหัส','ชื่อลูกค้า','ภูมิภาค','สถานะ'],rows)}</div>`}
function warehousePage(){
  const jobs=state.data.orders.filter(o=>['CONFIRMED','PARTIAL_ISSUE'].includes(o.status)).map(o=>{const ls=orderLines(o.id),rem=ls.reduce((s,l)=>s+Number(l.qty)-Number(l.issued_qty||0),0);return `<tr><td><b>${esc(o.order_no)}</b></td><td>${esc(customerName(o.customer_id))}</td><td class="num">${qty(rem)}</td><td>${badge(o.status)}</td><td><button class="btn primary small-btn" data-action="issueOrder" data-id="${o.id}">จ่ายสินค้า</button></td></tr>`});
  const rec=state.data.receipts.slice(0,8).map(r=>`<tr><td><b>${esc(r.gr_no)}</b></td><td>${esc(warehouse(r.warehouse_id).code)}</td><td>${esc(r.source_doc_no||'-')}</td><td>${dmy(r.receipt_date)}</td><td>${badge(r.status)}</td></tr>`);
  return head('งานคลัง','รับเข้า จ่ายออก และตรวจสอบงานค้าง','<button class="btn primary" data-action="newReceipt">+ รับสินค้า</button>')+cards([['รอจ่าย',nf.format(jobs.length),'Orders'],['รับเข้าวันนี้',nf.format(state.data.receipts.filter(x=>x.receipt_date===new Date().toISOString().slice(0,10)).length),'เอกสาร'],['Stock รวม',qty(state.data.balances.reduce((s,x)=>s+Number(x.on_hand),0)),'ทุกคลัง'],['โอนค้างรับ',nf.format(state.data.transfers.filter(x=>x.status==='IN_TRANSIT').length),'Transfers']])+`<div class="split"><div class="panel"><h3>งานรอจ่าย</h3>${table(['Order','ลูกค้า','คงเหลือต้องจ่าย','สถานะ',''],jobs)}</div><div class="panel"><h3>รับสินค้าล่าสุด</h3>${table(['GR','คลัง','เอกสารอ้างอิง','วันที่','สถานะ'],rec)}</div></div>`;
}
function stockPage(){
  const rows=state.data.balances.map(b=>{const p=product(b.product_id),w=warehouse(b.warehouse_id),avail=Number(b.on_hand)-Number(b.allocated);return `<tr><td><b>${esc(p.code)}</b> ${esc(p.name)}</td><td>${esc(w.code)} ${esc(w.name)}</td><td class="num" data-sort="${b.on_hand}">${qty(b.on_hand)}</td><td class="num">${qty(b.allocated)}</td><td class="num"><b>${qty(avail)}</b></td><td>${esc(p.base_uom||'')}</td></tr>`});
  const moves=state.data.movements.filter(m=>`${product(m.product_id).code} ${warehouse(m.warehouse_id).code} ${m.reference_no||''}`.toLowerCase().includes(state.search)).slice(0,100).map(m=>`<tr><td>${dmy(m.created_at)}</td><td>${esc(product(m.product_id).code)}</td><td>${esc(warehouse(m.warehouse_id).code)}</td><td>${esc(m.movement_type)}</td><td>${esc(m.reference_no||'-')}</td><td class="num ${Number(m.qty)<0?'negative':'positive'}" data-sort="${m.qty}">${qty(m.qty)}</td></tr>`);
  return head('Stock','ยอดคงเหลือและ Stock Movement แบบ Real-time','<button class="btn" data-action="exportStock">ดาวน์โหลด CSV</button>')+`<div class="panel"><h3>ยอดคงเหลือ</h3>${table(['สินค้า','คลัง','On Hand','Allocated','Available','UoM'],rows)}</div><div class="panel"><div class="page-head"><div><h3>Stock Movement</h3></div><input id="pageSearch" placeholder="ค้นหาสินค้า / คลัง / เอกสาร"></div>${table(['วันที่','สินค้า','คลัง','ประเภท','อ้างอิง','จำนวน'],moves)}</div>`;
}
function countsPage(){const rows=state.data.counts.map(c=>{const ls=state.data.countLines.filter(x=>x.count_id===c.id),variance=ls.reduce((s,x)=>s+Number(x.count_qty||0)-Number(x.book_qty||0),0);return `<tr><td><b>${esc(c.count_no)}</b></td><td>${esc(warehouse(c.warehouse_id).code)}</td><td>${dmy(c.snapshot_at)}</td><td class="num">${nf.format(ls.length)}</td><td class="num ${variance?'negative':''}">${qty(variance)}</td><td>${badge(c.status)}</td></tr>`});return head('ตรวจนับ Stock','ปรับยอดตามจำนวนที่นับจริง พร้อมบังคับเหตุผลส่วนต่าง','<button class="btn primary" data-action="newCount">+ เริ่มตรวจนับ</button>')+`<div class="alert warn">เมื่อยืนยัน ระบบจะสร้าง Stock Adjustment และ Audit Log ทันที</div><div class="panel">${table(['Count No.','คลัง','วันเวลา','สินค้า','ส่วนต่างสุทธิ','สถานะ'],rows)}</div>`}
function transfersPage(){const rows=state.data.transfers.map(t=>{const l=transferLine(t.id)||{};return `<tr><td><b>${esc(t.transfer_no)}</b></td><td>${esc(warehouse(t.from_warehouse_id).code)}</td><td>${esc(warehouse(t.to_warehouse_id).code)}</td><td>${esc(product(l.product_id).code||'-')}</td><td class="num">${qty(l.sent_qty)}</td><td class="num">${l.received_qty==null?'-':qty(l.received_qty)}</td><td>${badge(t.status)}</td><td>${t.status==='IN_TRANSIT'?`<button class="btn primary small-btn" data-action="receiveTransfer" data-id="${t.id}">รับปลายทาง</button>`:''}</td></tr>`});return head('โอนระหว่างคลัง','ตัดต้นทางเมื่อส่ง และเพิ่มปลายทางเมื่อรับจริง','<button class="btn primary" data-action="newTransfer">+ สร้างใบโอน</button>')+`<div class="panel">${table(['Transfer','จาก','ไป','สินค้า','ส่ง','รับจริง','สถานะ',''],rows)}</div>`}
function deliveryPage(){
  const ready=state.data.orders.filter(o=>o.status==='WAITING_LOGISTICS').map(o=>`<tr><td><b>${esc(o.order_no)}</b></td><td>${esc(customerName(o.customer_id))}</td><td>${dmy(o.requested_delivery_at)}</td><td class="num">${qty(orderLines(o.id).reduce((s,l)=>s+Number(l.issued_qty||0),0))}</td><td>${can('LOGISTICS','ADMIN')?`<button class="btn primary small-btn" data-action="newTrip" data-id="${o.id}">จัดรถ</button>`:''}</td></tr>`);
  const trips=state.data.trips.map(t=>{const o=byId('orders',t.order_id),doc=state.data.deliveryDocs?.find(d=>d.trip_id===t.id);return `<tr><td><b>${esc(t.trip_no)}</b></td><td>${esc(o?.order_no||'-')}</td><td>${esc(customerName(o?.customer_id))}</td><td>${dmy(t.planned_start)}</td><td>${esc(byId('vehicles',t.vehicle_id)?.plate_no||'-')}</td><td>${badge(t.status)}</td><td>${t.status!=='COMPLETED'&&can('LOGISTICS','ADMIN')?`<button class="btn primary small-btn" data-action="completeTrip" data-id="${t.id}">POD / ปิดงาน</button>`:doc?`<button class="btn small-btn" data-action="openPod" data-id="${doc.id}">เปิด POD</button>`:esc(t.pod_reference||'-')}</td></tr>`});
  return head('ขนส่ง / POD','จัดรถ ตรวจเวลาซ้อน และบันทึกลูกค้ารับจริง')+`<div class="split"><div class="panel"><h3>รอจัดรถ</h3>${table(['Order','ลูกค้า','กำหนดส่ง','จำนวน',''],ready)}</div><div class="panel"><h3>เที่ยวส่ง</h3>${table(['Trip','Order','ลูกค้า','เวลา','รถ','สถานะ',''],trips)}</div></div>`;
}
function profitPage(){const rows=state.data.invoices.map(i=>{const gp=Number(i.revenue)-Number(i.product_cost)-Number(i.freight_cost)-Number(i.other_cost),pct=Number(i.revenue)?gp/Number(i.revenue)*100:0;return `<tr><td><b>${esc(i.invoice_no)}</b></td><td>${dmy(i.invoice_date)}</td><td>${esc(customerName(i.customer_id))}</td><td class="num">${money(i.revenue)}</td><td class="num">${money(i.product_cost)}</td><td class="num">${money(i.freight_cost)}</td><td class="num">${money(i.other_cost)}</td><td class="num"><b>${money(gp)}</b></td><td class="num">${pct.toFixed(2)}%</td><td>${badge(i.gp_status)}</td></tr>`});const rev=state.data.invoices.reduce((s,x)=>s+Number(x.revenue),0),gp=state.data.invoices.reduce((s,x)=>s+Number(x.revenue)-Number(x.product_cost)-Number(x.freight_cost)-Number(x.other_cost),0);return head('Sales & Profit','Revenue − Product Cost − Freight − Other Cost','<button class="btn" data-action="exportProfit">ดาวน์โหลด CSV</button><button class="btn" data-action="printReport">พิมพ์ / PDF</button>')+cards([['Revenue',money(rev),''],['Gross Profit',money(gp),''],['GP %',rev?(gp/rev*100).toFixed(2)+'%':'0%',''],['Invoice',nf.format(state.data.invoices.length),'']])+`<div class="panel">${table(['Invoice','วันที่','ลูกค้า','Revenue','Product Cost','Freight','Other','GP','GP%','สถานะ'],rows)}</div>`}
function mastersPage(){const tabs=[['customers','Customer'],['products','Product'],['warehouses','Warehouse'],['suppliers','Vendor'],['vehicles','Vehicle'],['drivers','Driver'],['costs','Monthly Cost']];const cardsHtml=tabs.map(x=>`<div class="card"><div class="label">${x[1]}</div><div class="value">${nf.format(state.data[x[0]].length)}</div><button class="btn small-btn" style="margin-top:12px" data-action="manageMaster" data-id="${x[0]}">เปิดข้อมูล</button></div>`).join('');return head('Master Data','ข้อมูลกลางสำหรับใช้งานทุก Module')+`<div class="cards">${cardsHtml}</div><div class="alert warn">การแก้ Master มีผลกับรายการใหม่ทันที รายการย้อนหลังยังคงรหัสอ้างอิงเดิม</div>`}
function usersPage(){const pending=state.data.accessRequests.filter(x=>x.status==='PENDING').map(x=>`<tr><td><b>${esc(x.full_name)}</b><br><span class="muted">${esc(x.email)}</span></td><td>${esc(x.employee_code||'-')}</td><td>${esc(roleThai[x.requested_role]||x.requested_role)}</td><td><select id="approveRole-${x.id}">${['SALES','WAREHOUSE','LOGISTICS','OWNER','ADMIN'].map(r=>`<option value="${r}" ${r===x.requested_role?'selected':''}>${roleThai[r]}</option>`).join('')}</select></td><td><button class="btn primary small-btn" data-action="approveUser" data-id="${x.id}">อนุมัติ</button> <button class="btn danger small-btn" data-action="rejectUser" data-id="${x.id}">ปฏิเสธ</button></td></tr>`);const users=(state.data.users||[]).map(u=>`<tr><td><b>${esc(u.full_name)}</b><br><span class="muted">${esc(u.email||'-')}</span></td><td>${esc(u.employee_code||'-')}</td><td><select id="userRole-${u.user_id}">${['SALES','WAREHOUSE','LOGISTICS','OWNER','ADMIN'].map(r=>`<option value="${r}" ${r===u.app_role?'selected':''}>${roleThai[r]}</option>`).join('')}</select></td><td>${u.active?badge('ACTIVE'):badge('INACTIVE')}</td><td><button class="btn small-btn" data-action="saveUser" data-id="${u.user_id}" data-active="${u.active?'1':'0'}">บันทึกสิทธิ์</button> <button class="btn ${u.active?'danger':''} small-btn" data-action="toggleUser" data-id="${u.user_id}" data-active="${u.active?'1':'0'}">${u.active?'ปิดใช้งาน':'เปิดใช้งาน'}</button></td></tr>`);return head('Users / Roles','ผู้ใช้สมัครเองและเริ่มใช้งานได้เมื่อ Admin อนุมัติ')+cards([['รออนุมัติ',nf.format(pending.length),'คำขอ'],['ผู้ใช้งาน',nf.format(users.length),'บัญชี']])+`<div class="panel"><h3>คำขอเปิดใช้งาน</h3>${table(['ผู้ขอ','รหัส','ขอสิทธิ์','กำหนดสิทธิ์',''],pending)}</div><div class="panel"><h3>ผู้ใช้ในระบบ</h3>${table(['ผู้ใช้','รหัส','บทบาท','สถานะ',''],users)}</div>`}
function settingsPage(){const current=new Date().toISOString().slice(0,7),periodRows=state.data.periods.map(p=>`<tr><td><b>${dmy(p.period_month)}</b></td><td>${badge(p.status)}</td><td>${dmy(p.closed_at)}</td><td>${esc(p.reopen_reason||'-')}</td><td><button class="btn small-btn ${p.status==='OPEN'?'danger':''}" data-action="togglePeriod" data-id="${p.period_month}" data-status="${p.status}">${p.status==='OPEN'?'Close Month':'Reopen'}</button></td></tr>`);return head('ตั้งค่าระบบ','Business Rules และการควบคุมงวด')+cards([['แพ็กเกจ',esc(state.company.subscription_plan||'DEMO'),''],['สถานะ',esc(state.company.subscription_status||'DEMO'),state.company.trial_ends_at?`สิ้นสุด ${dmy(state.company.trial_ends_at)}`:''],['ผู้ใช้สูงสุด',nf.format(state.company.max_users||0),'บัญชี'],['รหัสบริษัท',esc(state.company.code||'-'),'ใช้สมัครสมาชิกในบริษัท']])+`<div class="split"><div class="panel"><h3>Business Rules ที่ใช้งาน</h3><table><tbody><tr><td>Stock Issue</td><td><b>Strict — ห้ามติดลบ</b></td></tr><tr><td>Partial Issue</td><td>อนุญาต พร้อมแสดงยอดค้าง</td></tr><tr><td>Revenue Qty</td><td>Customer Received Qty</td></tr><tr><td>GP Policy</td><td>${esc(state.company.gp_policy)}</td></tr><tr><td>Duplicate Submit</td><td>ป้องกันด้วย Request ID</td></tr><tr><td>POD Storage</td><td>Private • PDF/JPG/PNG • สูงสุด 10 MB</td></tr></tbody></table></div><div class="panel"><h3>ล็อกงวด</h3><div class="form"><label>เดือน<input id="newPeriodMonth" type="month" value="${current}"></label></div><button class="btn danger" data-action="closeNewPeriod">Close Month</button><p class="muted">เมื่อปิดงวด ระบบห้ามสร้าง/แก้ Order, GR, Invoice และ Monthly Cost ในเดือนนั้น</p></div></div><div class="panel"><h3>ประวัติงวด</h3>${table(['เดือน','สถานะ','วันที่ปิด','เหตุผล Reopen',''],periodRows)}</div>`}
function auditPage(){const rows=(state.data.audit||[]).map(x=>`<tr><td>${dmy(x.created_at)}</td><td><b>${esc(x.action)}</b></td><td>${esc(x.entity_type||'-')}</td><td>${esc(x.entity_id||'-')}</td><td>${esc(x.user_id||'-')}</td></tr>`);return head('Audit Log','ประวัติธุรกรรมสำคัญ แก้ย้อนหลังไม่ได้','<button class="btn" data-action="exportAudit">ดาวน์โหลด CSV</button>')+`<div class="panel">${table(['วันเวลา','Action','ประเภท','รายการ','User'],rows)}</div>`}
function inactivePage(){return head('ระงับการใช้งาน','บริษัทนี้หมดอายุหรือถูกระงับชั่วคราว')+'<div class="panel"><div class="alert danger">กรุณาติดต่อผู้ดูแล FlowStock เพื่อเปิดใช้งานแพ็กเกจ ระบบยังเก็บข้อมูลเดิมไว้และไม่อนุญาตให้ทำธุรกรรมใหม่</div></div>'}
function commercialPage(){if(!state.isPlatformAdmin)return empty('ไม่มีสิทธิ์ใช้งาน');const rows=(state.data.tenants||[]).map(c=>`<tr><td><b>${esc(c.code)}</b></td><td>${esc(c.name)}</td><td>${esc(c.subscription_plan)}</td><td>${badge(c.subscription_status)}</td><td class="num">${nf.format(c.active_users)} / ${nf.format(c.max_users)}</td><td>${c.trial_ends_at?dmy(c.trial_ends_at):'-'}</td><td>${c.is_demo?'Demo':`<button class="btn small-btn" data-action="manageTenant" data-id="${c.id}">จัดการ</button>`}</td></tr>`);return head('Commercial Control','สร้างและควบคุมบริษัทลูกค้า','<button class="btn primary" data-action="newTenant">+ เปิดบริษัทลูกค้า</button>')+cards([['บริษัททั้งหมด',nf.format(state.data.tenants?.length||0),'Tenant'],['ใช้งานจริง',nf.format((state.data.tenants||[]).filter(x=>x.subscription_status==='ACTIVE').length),'บริษัท'],['ทดลองใช้',nf.format((state.data.tenants||[]).filter(x=>x.subscription_status==='TRIAL').length),'บริษัท'],['ระงับ/หมดอายุ',nf.format((state.data.tenants||[]).filter(x=>['SUSPENDED','EXPIRED'].includes(x.subscription_status)).length),'บริษัท']])+`<div class="panel">${table(['รหัส','บริษัท','แพ็กเกจ','สถานะ','ผู้ใช้','Trial End',''],rows)}</div>`}

const actions={
  newOrder(){orderModal()},viewOrder(id){viewOrder(id)},newReceipt(){receiptModal()},issueOrder(id){issueModal(id)},newCount(){countModal()},newTransfer(){transferModal()},receiveTransfer(id){receiveTransferModal(id)},newTrip(id){tripModal(id)},completeTrip(id){completeTripModal(id)},openPod(id){openPod(id)},manageMaster(id){masterModal(id)},approveUser(id){approveUser(id)},rejectUser(id){rejectUser(id)},saveUser(id){saveUser(id,true)},toggleUser(id){const b=document.querySelector(`[data-action="toggleUser"][data-id="${id}"]`);saveUser(id,b?.dataset.active!=='1')},closeNewPeriod(){setPeriod($('#newPeriodMonth').value+'-01','CLOSED')},togglePeriod(id){const b=document.querySelector(`[data-action="togglePeriod"][data-id="${id}"]`);if(b?.dataset.status==='OPEN')setPeriod(id,'CLOSED');else reopenPeriod(id)},exportOrders(){exportOrders()},exportStock(){exportStock()},exportProfit(){exportProfit()},exportAudit(){exportAudit()},printReport(){window.print()},newTenant(){tenantModal()},manageTenant(id){manageTenantModal(id)}
};
function option(list,label,val='id'){return state.data[list].filter(x=>x.active!==false).map(x=>`<option value="${x[val]}">${esc(label(x))}</option>`).join('')}
function orderLineHtml(){return `<div class="line-editor order-line"><label>สินค้า<select class="ol-product">${option('products',x=>`${x.code} • ${x.name}`)}</select></label><label>คลัง<select class="ol-wh">${option('warehouses',x=>`${x.code} • ${x.name}`)}</select></label><label>จำนวน<input class="ol-qty" type="number" min="0.0001" step="any" required></label><label>ราคา/หน่วย<input class="ol-price" type="number" min="0" step="any" required></label><button type="button" class="btn danger remove-line">ลบ</button></div>`}
function wireLines(kind){const area=$(`#${kind}Lines`);area.querySelectorAll('.remove-line').forEach(b=>b.onclick=()=>{if(area.children.length>1)b.parentElement.remove()});if(kind==='order')area.querySelectorAll('select,input').forEach(el=>el.onchange=updateOrderStock)}
function orderModal(){modal(`<h2>สร้าง Order</h2><p class="muted">รองรับหลายสินค้า ระบบเตือน Stock แต่ยังสร้าง Order ได้</p><form id="orderForm"><div class="form"><label>ลูกค้า<select id="oCustomer" required>${option('customers',x=>`${x.code} • ${x.name}`)}</select></label><label>วันที่ Order<input id="oDate" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><label>กำหนดส่ง<input id="oDelivery" type="datetime-local" value="${localInput(86400000)}"></label></div><h3>รายการสินค้า</h3><div id="orderLines">${orderLineHtml()}</div><button type="button" id="addOrderLine" class="btn">+ เพิ่มสินค้า</button><div id="orderStockNote" class="alert warn"></div><div class="actions" style="margin-top:18px"><button class="btn primary" type="submit">ยืนยัน Order</button><button id="cancelOrder" class="btn" type="button">ยกเลิก</button></div></form>`);$('#addOrderLine').onclick=()=>{$('#orderLines').insertAdjacentHTML('beforeend',orderLineHtml());wireLines('order');updateOrderStock()};$('#cancelOrder').onclick=closeModal;wireLines('order');updateOrderStock();$('#orderForm').onsubmit=saveOrder}
function updateOrderStock(){const notes=$$('.order-line').map(r=>{const p=r.querySelector('.ol-product').value,w=r.querySelector('.ol-wh').value,q=Number(r.querySelector('.ol-qty').value||0),a=stockAvailable(p,w);return `${product(p).code||''} / ${warehouse(w).code||''}: Available ${qty(a)}${q>a?` • ขาด ${qty(q-a)}`:''}`});$('#orderStockNote').innerHTML=notes.join('<br>')}
async function saveOrder(e){e.preventDefault();const lines=$$('.order-line').map(r=>({product_id:r.querySelector('.ol-product').value,warehouse_id:r.querySelector('.ol-wh').value,qty:Number(r.querySelector('.ol-qty').value),unit_price:Number(r.querySelector('.ol-price').value)}));if(lines.some(x=>!x.qty||x.unit_price<0))return toast('กรอกจำนวนและราคาให้ครบ',true);await runRpc('create_order',{p_customer_id:$('#oCustomer').value,p_order_date:$('#oDate').value,p_requested_delivery_at:new Date($('#oDelivery').value).toISOString(),p_lines:lines,p_request_id:requestId('ORDER')},r=>`สร้าง ${r.order_no} สำเร็จ`)}
function viewOrder(id){const o=byId('orders',id),rows=orderLines(id).map(l=>`<tr><td>${esc(product(l.product_id).code)} ${esc(product(l.product_id).name)}</td><td>${esc(warehouse(l.warehouse_id).code)}</td><td class="num">${qty(l.qty)}</td><td class="num">${qty(l.issued_qty)}</td><td class="num">${money(l.unit_price)}</td><td class="num">${money(Number(l.qty)*Number(l.unit_price))}</td></tr>`);modal(`<h2>${esc(o.order_no)}</h2><p>${esc(customerName(o.customer_id))} • ${badge(o.status)}</p>${table(['สินค้า','คลัง','Order Qty','Issued','ราคา','มูลค่า'],rows)}`)}
function receiptLineHtml(){return `<div class="line-editor receipt-line"><label>สินค้า<select class="gr-product">${option('products',x=>`${x.code} • ${x.name}`)}</select></label><label>จำนวน<input class="gr-qty" type="number" min="0.0001" step="any" required></label><label>Unit Cost<input class="gr-cost" type="number" min="0" step="any"></label><span></span><button type="button" class="btn danger remove-line">ลบ</button></div>`}
function receiptModal(){modal(`<h2>รับสินค้าเข้าคลัง</h2><form id="receiptForm"><div class="form"><label>คลัง<select id="grWh">${option('warehouses',x=>`${x.code} • ${x.name}`)}</select></label><label>Vendor<select id="grSupplier"><option value="">— ไม่ระบุ —</option>${option('suppliers',x=>`${x.code} • ${x.name}`)}</select></label><label>เอกสารอ้างอิง<input id="grRef" required></label><label>วันที่รับ<input id="grDate" type="date" value="${new Date().toISOString().slice(0,10)}" required></label></div><h3>รายการสินค้า</h3><div id="receiptLines">${receiptLineHtml()}</div><button type="button" id="addReceiptLine" class="btn">+ เพิ่มสินค้า</button><div class="actions" style="margin-top:18px"><button class="btn primary">ยืนยันรับสินค้า</button></div></form>`);$('#addReceiptLine').onclick=()=>{$('#receiptLines').insertAdjacentHTML('beforeend',receiptLineHtml());wireLines('receipt')};wireLines('receipt');$('#receiptForm').onsubmit=async e=>{e.preventDefault();const lines=$$('.receipt-line').map(r=>({product_id:r.querySelector('.gr-product').value,qty:Number(r.querySelector('.gr-qty').value),unit_cost:r.querySelector('.gr-cost').value||null}));await runRpc('post_goods_receipt',{p_warehouse_id:$('#grWh').value,p_supplier_id:$('#grSupplier').value||null,p_source_doc_no:$('#grRef').value.trim(),p_receipt_date:$('#grDate').value,p_lines:lines,p_request_id:requestId('GR')},r=>`รับสินค้า ${r.gr_no} สำเร็จ`)}}
function issueModal(id){const o=byId('orders',id),rows=orderLines(id).filter(l=>Number(l.qty)>Number(l.issued_qty)).map(l=>`<div class="line-editor issue-line" data-id="${l.id}"><label>สินค้า<input value="${esc(product(l.product_id).code)} • ${esc(product(l.product_id).name)}" disabled></label><label>Available<input value="${qty(stockAvailable(l.product_id,l.warehouse_id))}" disabled></label><label>คงเหลือต้องจ่าย<input value="${qty(Number(l.qty)-Number(l.issued_qty))}" disabled></label><label>จ่ายครั้งนี้<input class="issue-qty" type="number" min="0.0001" max="${Number(l.qty)-Number(l.issued_qty)}" step="any" value="${Math.min(Number(l.qty)-Number(l.issued_qty),stockAvailable(l.product_id,l.warehouse_id))}" required></label></div>`).join('');modal(`<h2>จ่ายสินค้า ${esc(o.order_no)}</h2><div class="alert warn">ระบบห้าม Stock ติดลบ หากของไม่พอสามารถจ่ายบางส่วนได้</div><form id="issueForm">${rows}<div class="actions"><button class="btn primary">ยืนยันตัด Stock</button></div></form>`);$('#issueForm').onsubmit=async e=>{e.preventDefault();const lines=$$('.issue-line').map(r=>({order_line_id:r.dataset.id,qty:Number(r.querySelector('.issue-qty').value)})).filter(x=>x.qty>0);await runRpc('issue_order',{p_order_id:id,p_lines:lines,p_request_id:requestId('ISSUE')},r=>`จ่ายสินค้าแล้ว • ${statusThai[r.status]||r.status}`)}}
function countModal(){modal(`<h2>ตรวจนับ Stock</h2><form id="countForm"><div class="form"><label>คลัง<select id="countWh">${option('warehouses',x=>`${x.code} • ${x.name}`)}</select></label></div><div class="alert warn">กรอกจำนวนที่นับจริง ระบบจะแสดงยอดตามบัญชีและส่วนต่าง</div><div id="countLines"></div><button class="btn primary">ยืนยันผลตรวจนับ</button></form>`);const renderLines=()=>{const wid=$('#countWh').value;$('#countLines').innerHTML=state.data.products.filter(x=>x.active!==false).map(p=>{const book=state.data.balances.find(b=>b.warehouse_id===wid&&b.product_id===p.id)?.on_hand||0;return `<div class="line-editor count-line" data-id="${p.id}" data-book="${book}"><label>สินค้า<input value="${esc(p.code)} • ${esc(p.name)}" disabled></label><label>Book Qty<input value="${qty(book)}" disabled></label><label>Count Qty<input class="count-qty" type="number" min="0" step="any" value="${book}" required></label><label>เหตุผลส่วนต่าง<input class="count-reason" placeholder="บังคับเมื่อมียอดต่าง"></label></div>`}).join('')};$('#countWh').onchange=renderLines;renderLines();$('#countForm').onsubmit=async e=>{e.preventDefault();const lines=$$('.count-line').map(r=>({product_id:r.dataset.id,count_qty:Number(r.querySelector('.count-qty').value),variance_reason:r.querySelector('.count-reason').value.trim()||null}));await runRpc('post_stock_count',{p_warehouse_id:$('#countWh').value,p_lines:lines,p_request_id:requestId('COUNT')},r=>`บันทึก ${r.count_no} สำเร็จ`)}}
function transferModal(){modal(`<h2>สร้างใบโอนคลัง</h2><form id="transferForm"><div class="form"><label>คลังต้นทาง<select id="trFrom">${option('warehouses',x=>`${x.code} • ${x.name}`)}</select></label><label>คลังปลายทาง<select id="trTo">${option('warehouses',x=>`${x.code} • ${x.name}`)}</select></label><label>สินค้า<select id="trProduct">${option('products',x=>`${x.code} • ${x.name}`)}</select></label><label>จำนวนส่ง<input id="trQty" type="number" min="0.0001" step="any" required></label></div><div id="trAvailable" class="alert warn"></div><button class="btn primary">ยืนยันส่งโอน</button></form>`);const update=()=>$('#trAvailable').textContent=`Available ต้นทาง ${qty(stockAvailable($('#trProduct').value,$('#trFrom').value))}`;$('#trFrom').onchange=update;$('#trProduct').onchange=update;update();$('#transferForm').onsubmit=async e=>{e.preventDefault();await runRpc('create_transfer',{p_from_warehouse_id:$('#trFrom').value,p_to_warehouse_id:$('#trTo').value,p_product_id:$('#trProduct').value,p_qty:Number($('#trQty').value),p_request_id:requestId('TRANSFER')},r=>`สร้าง ${r.transfer_no} สำเร็จ`)}}
function receiveTransferModal(id){const t=byId('transfers',id),l=transferLine(id);modal(`<h2>รับโอน ${esc(t.transfer_no)}</h2><form id="receiveTransferForm"><div class="form"><label>จำนวนส่ง<input value="${qty(l.sent_qty)}" disabled></label><label>จำนวนรับจริง<input id="trReceived" type="number" min="0" max="${l.sent_qty}" step="any" value="${l.sent_qty}" required></label><label class="full">เหตุผลส่วนต่าง<input id="trReason" placeholder="บังคับเมื่อรับไม่เท่าจำนวนส่ง"></label></div><button class="btn primary">ยืนยันรับปลายทาง</button></form>`);$('#receiveTransferForm').onsubmit=async e=>{e.preventDefault();await runRpc('receive_transfer',{p_transfer_id:id,p_received_qty:Number($('#trReceived').value),p_variance_reason:$('#trReason').value.trim()||null,p_request_id:requestId('TRRECV')},r=>`รับ ${r.transfer_no} สำเร็จ • ส่วนต่าง ${qty(r.variance)}`)}}
function tripModal(orderId){const o=byId('orders',orderId);modal(`<h2>จัดรถ ${esc(o.order_no)}</h2><form id="tripForm"><div class="form"><label>รถ<select id="tripVehicle"><option value="">— รถ Vendor / ไม่ระบุ —</option>${option('vehicles',x=>`${x.code} • ${x.plate_no||''} ${x.vehicle_type||''}`)}</select></label><label>คนขับ<select id="tripDriver"><option value="">— ไม่ระบุ —</option>${option('drivers',x=>`${x.code} • ${x.name}`)}</select></label><label>Vendor ขนส่ง<select id="tripVendor"><option value="">— รถบริษัท —</option>${option('suppliers',x=>`${x.code} • ${x.name}`)}</select></label><label>Standard Freight<input id="tripStd" type="number" min="0" step="any" value="0"></label><label>เวลาเริ่ม<input id="tripStart" type="datetime-local" value="${localInput(3600000)}" required></label><label>เวลาสิ้นสุด<input id="tripEnd" type="datetime-local" value="${localInput(14400000)}" required></label></div><button class="btn primary">ยืนยันจัดรถ</button></form>`);$('#tripForm').onsubmit=async e=>{e.preventDefault();await runRpc('create_delivery_trip',{p_order_id:orderId,p_vehicle_id:$('#tripVehicle').value||null,p_driver_id:$('#tripDriver').value||null,p_transport_supplier_id:$('#tripVendor').value||null,p_planned_start:new Date($('#tripStart').value).toISOString(),p_planned_end:new Date($('#tripEnd').value).toISOString(),p_standard_freight:Number($('#tripStd').value||0),p_request_id:requestId('TRIP')},r=>`จัดรถ ${r.trip_no} สำเร็จ`)}}
function completeTripModal(id){const t=byId('trips',id),lines=tripLines(id).map(l=>`<div class="line-editor pod-line" data-id="${l.id}"><label>สินค้า<input value="${esc(product(l.product_id).code)} • ${esc(product(l.product_id).name)}" disabled></label><label>Warehouse Issue<input value="${qty(l.issued_qty)}" disabled></label><label>ลูกค้ารับจริง<input class="pod-qty" type="number" min="0" max="${l.issued_qty}" step="any" value="${l.issued_qty}" required></label><label>เหตุผลส่วนต่าง<input class="pod-reason" placeholder="Loss / Return / Pending"></label></div>`).join('');modal(`<h2>POD / ปิดงาน ${esc(t.trip_no)}</h2><form id="podForm">${lines}<div class="form"><label>Actual Freight<input id="actualFreight" type="number" min="0" step="any" value="${t.standard_freight||0}" required></label><label>เลขที่ POD<input id="podRef" placeholder="เลขที่เอกสาร (ถ้ามี)"></label><label class="full">ไฟล์ POD (PDF/JPG/PNG ไม่เกิน 10 MB)<input id="podFile" type="file" accept="application/pdf,image/jpeg,image/png" required></label></div><div class="alert warn">ไฟล์เก็บใน Private Storage แยกตามบริษัท Revenue และ Product Cost คำนวณจากจำนวนที่ลูกค้ารับจริง</div><button class="btn primary">อัปโหลด POD และยืนยันส่งสำเร็จ</button></form>`);$('#podForm').onsubmit=e=>completeTrip(e,id)}
const masterMeta={customers:['Customer','code,name,region','รหัส,ชื่อ,ภูมิภาค'],products:['Product','code,name,base_uom','รหัส,ชื่อ,หน่วย'],warehouses:['Warehouse','code,name','รหัส,ชื่อ'],suppliers:['Vendor','code,name,supplier_type','รหัส,ชื่อ,ประเภท'],vehicles:['Vehicle','code,plate_no,vehicle_type','รหัส,ทะเบียน,ประเภทรถ'],drivers:['Driver','code,name,phone','รหัส,ชื่อ,โทรศัพท์']};
function masterModal(kind){if(kind==='costs')return costModal();const [title,fields,labels]=masterMeta[kind],fs=fields.split(','),ls=labels.split(','),rows=state.data[kind].map(x=>`<tr>${fs.map(f=>`<td>${esc(x[f]||'-')}</td>`).join('')}<td>${x.active===false?'ปิด':'ใช้งาน'}</td></tr>`);modal(`<h2>${title}</h2><form id="masterForm"><div class="form">${fs.map((f,i)=>`<label>${ls[i]}<input data-field="${f}" required></label>`).join('')}</div><button class="btn primary" style="margin:16px 0">+ เพิ่ม ${title}</button></form>${table([...ls,'สถานะ'],rows)}`);$('#masterForm').onsubmit=async e=>{e.preventDefault();const obj={company_id:state.profile.company_id,active:true};$$('#masterForm [data-field]').forEach(x=>obj[x.dataset.field]=x.value.trim());const {error}=await db.from(kind).insert(obj);if(error)return fail(error);toast(`เพิ่ม ${title} แล้ว`);closeModal();await loadData();render()}}
function costModal(){const rows=state.data.costs.map(x=>`<tr><td>${esc(product(x.product_id).code)}</td><td>${dmy(x.cost_month)}</td><td class="num">${money(x.unit_cost)}</td><td>${x.locked?'ล็อก':'เปิด'}</td></tr>`);modal(`<h2>Monthly Product Cost</h2><form id="costForm"><div class="form"><label>สินค้า<select id="costProduct">${option('products',x=>`${x.code} • ${x.name}`)}</select></label><label>เดือน<input id="costMonth" type="month" value="${new Date().toISOString().slice(0,7)}" required></label><label>Unit Cost<input id="unitCost" type="number" min="0" step="any" required></label></div><button class="btn primary" style="margin:16px 0">บันทึก Cost</button></form>${table(['สินค้า','เดือน','Unit Cost','สถานะ'],rows)}`);$('#costForm').onsubmit=async e=>{e.preventDefault();const data={company_id:state.profile.company_id,product_id:$('#costProduct').value,cost_month:$('#costMonth').value+'-01',unit_cost:Number($('#unitCost').value)};const {error}=await db.from('monthly_product_costs').upsert(data,{onConflict:'company_id,product_id,cost_month'});if(error)return fail(error);toast('บันทึก Monthly Cost แล้ว');closeModal();await loadData();render()}}
async function forgotPassword(){const email=$('#email').value.trim()||prompt('กรอกอีเมลที่ใช้ใน FlowStock');if(!email)return;setLoading(true);const redirectTo=location.origin+location.pathname;const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo});setLoading(false);if(error)return fail(error);toast('ส่งลิงก์ตั้งรหัสผ่านใหม่แล้ว กรุณาตรวจอีเมล')}
function passwordRecoveryModal(){modal('<h2>ตั้งรหัสผ่านใหม่</h2><form id="recoveryForm"><div class="form"><label class="full">รหัสผ่านใหม่อย่างน้อย 8 ตัวอักษร<input id="recoveryPassword" type="password" minlength="8" required></label></div><button class="btn primary">บันทึกรหัสผ่านใหม่</button></form>');$('#recoveryForm').onsubmit=async e=>{e.preventDefault();setLoading(true);const {error}=await db.auth.updateUser({password:$('#recoveryPassword').value});setLoading(false);if(error)return fail(error);toast('เปลี่ยนรหัสผ่านแล้ว');closeModal()}}
function csvCell(v){const s=String(v??'');return `"${s.replaceAll('"','""')}"`}
function downloadCsv(name,headers,rows){const csv='\ufeff'+[headers,...rows].map(r=>r.map(csvCell).join(',')).join('\r\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportOrders(){downloadCsv('FlowStock_Orders.csv',['Order','Customer','Order Date','Status','Amount THB'],state.data.orders.map(o=>[o.order_no,customerName(o.customer_id),o.order_date,o.status,orderLines(o.id).reduce((s,l)=>s+Number(l.qty)*Number(l.unit_price),0)]))}
function exportStock(){downloadCsv('FlowStock_Stock.csv',['Product Code','Product Name','Warehouse','On Hand','Allocated','Available','UoM'],state.data.balances.map(b=>{const p=product(b.product_id),w=warehouse(b.warehouse_id);return[p.code,p.name,w.code,Number(b.on_hand),Number(b.allocated),Number(b.on_hand)-Number(b.allocated),p.base_uom]}))}
function exportProfit(){downloadCsv('FlowStock_Profit.csv',['Invoice','Date','Customer','Revenue','Product Cost','Freight','Other Cost','Gross Profit','GP %','Status'],state.data.invoices.map(i=>{const gp=Number(i.revenue)-Number(i.product_cost)-Number(i.freight_cost)-Number(i.other_cost);return[i.invoice_no,i.invoice_date,customerName(i.customer_id),i.revenue,i.product_cost,i.freight_cost,i.other_cost,gp,Number(i.revenue)?(gp/Number(i.revenue)*100).toFixed(2):0,i.gp_status]}))}
function exportAudit(){downloadCsv('FlowStock_Audit_Log.csv',['Timestamp','Action','Entity Type','Entity ID','User ID'],(state.data.audit||[]).map(x=>[x.created_at,x.action,x.entity_type,x.entity_id,x.user_id]))}
async function completeTrip(e,id){e.preventDefault();const file=$('#podFile').files[0];if(!file||!['application/pdf','image/jpeg','image/png'].includes(file.type)||file.size>10485760)return toast('เลือกไฟล์ PDF/JPG/PNG ขนาดไม่เกิน 10 MB',true);const ext=({"application/pdf":"pdf","image/jpeg":"jpg","image/png":"png"})[file.type],path=`${state.profile.company_id}/${id}/${crypto.randomUUID()}.${ext}`,lines=$$('.pod-line').map(r=>({trip_line_id:r.dataset.id,received_qty:Number(r.querySelector('.pod-qty').value),variance_reason:r.querySelector('.pod-reason').value.trim()||null}));$('#modalBody').dataset.busy='1';setLoading(true);let completed=false;try{const {error:uploadError}=await db.storage.from('pod-documents').upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const ref=$('#podRef').value.trim();const {data,error}=await db.rpc('complete_delivery',{p_trip_id:id,p_lines:lines,p_actual_freight:Number($('#actualFreight').value),p_pod_reference:ref?`${ref} | ${path}`:path,p_request_id:requestId('POD')});if(error)throw error;completed=true;const {error:attachError}=await db.rpc('attach_delivery_document',{p_trip_id:id,p_object_path:path,p_original_name:file.name,p_mime_type:file.type,p_file_size:file.size});if(attachError)throw attachError;toast(`ปิดงานและสร้าง ${data.invoice_no} • ${data.gp_status}`);$('#modalBody').dataset.busy='0';closeModal();await loadData();render()}catch(err){if(!completed)await db.storage.from('pod-documents').remove([path]);fail(err)}finally{$('#modalBody').dataset.busy='0';setLoading(false)}}
async function openPod(id){const doc=state.data.deliveryDocs.find(x=>x.id===id);if(!doc)return toast('ไม่พบเอกสาร POD',true);setLoading(true);const {data,error}=await db.storage.from(doc.bucket_id).createSignedUrl(doc.object_path,300);setLoading(false);if(error)return fail(error);window.open(data.signedUrl,'_blank','noopener')}
function tenantModal(){modal(`<h2>เปิดบริษัทลูกค้า</h2><form id="tenantForm"><div class="form"><label>รหัสบริษัท<input id="tenantCode" minlength="3" maxlength="20" pattern="[A-Za-z0-9_-]+" required placeholder="เช่น ACME01"></label><label>ชื่อบริษัท<input id="tenantName" required></label><label>แพ็กเกจ<select id="tenantPlan"><option>STARTER</option><option>BUSINESS</option><option>ENTERPRISE</option></select></label><label>จำนวนผู้ใช้สูงสุด<input id="tenantMax" type="number" min="1" max="10000" value="10" required></label><label>ทดลองใช้ (วัน)<input id="tenantTrial" type="number" min="1" max="365" value="30" required></label></div><div class="alert warn">ระบบจะสร้างรหัสเปิดบริษัทสำหรับ Admin ใช้ได้ครั้งเดียวและหมดอายุใน 7 วัน</div><button class="btn primary">สร้างบริษัท</button></form>`);$('#tenantForm').onsubmit=async e=>{e.preventDefault();setLoading(true);const {data,error}=await db.rpc('platform_create_tenant',{p_code:$('#tenantCode').value,p_name:$('#tenantName').value,p_plan:$('#tenantPlan').value,p_trial_days:Number($('#tenantTrial').value),p_max_users:Number($('#tenantMax').value)});setLoading(false);if(error)return fail(error);await loadData();modal(`<h2>สร้างบริษัท ${esc(data.company_code)} สำเร็จ</h2><div class="alert ok">คัดลอกรหัสด้านล่างส่งให้ Admin บริษัท รหัสจะแสดงครั้งนี้ครั้งเดียว</div><label>รหัสเปิดบริษัท<input id="newTenantCode" value="${esc(data.onboarding_code)}" readonly></label><button id="copyTenantCode" class="btn primary wide">คัดลอกรหัส</button><p class="muted">หมดอายุ ${dmy(data.expires_at)}</p>`);$('#copyTenantCode').onclick=async()=>{await navigator.clipboard.writeText(data.onboarding_code);toast('คัดลอกรหัสแล้ว')}}}
function manageTenantModal(id){const c=state.data.tenants.find(x=>x.id===id);modal(`<h2>จัดการ ${esc(c.code)} • ${esc(c.name)}</h2><form id="tenantManageForm"><div class="form"><label>สถานะ<select id="manageStatus">${['TRIAL','ACTIVE','SUSPENDED','EXPIRED'].map(x=>`<option ${x===c.subscription_status?'selected':''}>${x}</option>`).join('')}</select></label><label>แพ็กเกจ<select id="managePlan">${['STARTER','BUSINESS','ENTERPRISE'].map(x=>`<option ${x===c.subscription_plan?'selected':''}>${x}</option>`).join('')}</select></label><label>จำนวนผู้ใช้สูงสุด<input id="manageMax" type="number" min="1" max="10000" value="${c.max_users}" required></label></div><div class="alert warn">SUSPENDED และ EXPIRED จะหยุดการเข้าถึงข้อมูลและการทำธุรกรรมทันที แต่ไม่ลบข้อมูล</div><button class="btn primary">บันทึก</button></form>`);$('#tenantManageForm').onsubmit=async e=>{e.preventDefault();await runRpc('platform_set_company_status',{p_company_id:id,p_status:$('#manageStatus').value,p_plan:$('#managePlan').value,p_max_users:Number($('#manageMax').value)},()=>`อัปเดต ${c.code} แล้ว`)}}
async function approveUser(id){const role=$(`#approveRole-${id}`).value;setLoading(true);const {data,error}=await db.rpc('approve_access',{p_request_id:id,p_app_role:role});setLoading(false);if(error)return fail(error);toast(`อนุมัติสิทธิ์ ${roleThai[data.role]} แล้ว`);await loadData();render()}
async function rejectUser(id){if(!confirm('ยืนยันปฏิเสธคำขอนี้?'))return;setLoading(true);const {error}=await db.rpc('reject_access',{p_request_id:id});setLoading(false);if(error)return fail(error);toast('ปฏิเสธคำขอแล้ว');await loadData();render()}
async function saveUser(id,active){const role=$(`#userRole-${id}`).value;setLoading(true);const {error}=await db.rpc('admin_update_user',{p_user_id:id,p_app_role:role,p_active:active});setLoading(false);if(error)return fail(error);toast('บันทึกสิทธิ์ผู้ใช้แล้ว');await loadData();render()}
async function setPeriod(date,status,reason=null){if(status==='CLOSED'&&!confirm(`ยืนยันปิดงวด ${date.slice(0,7)}? รายการในงวดนี้จะแก้ไขไม่ได้`))return;setLoading(true);const {error}=await db.rpc('set_period_status',{p_period_month:date,p_status:status,p_reason:reason});setLoading(false);if(error)return fail(error);toast(status==='CLOSED'?'ปิดงวดแล้ว':'เปิดงวดแล้ว');await loadData();render()}
function reopenPeriod(date){modal(`<h2>Reopen Period ${esc(date.slice(0,7))}</h2><form id="reopenForm"><div class="form"><label class="full">เหตุผลที่เปิดงวดใหม่<textarea id="reopenReason" required></textarea></label></div><button class="btn primary">ยืนยัน Reopen</button></form>`);$('#reopenForm').onsubmit=async e=>{e.preventDefault();await setPeriod(date,'OPEN',$('#reopenReason').value.trim());closeModal()}}
async function runRpc(name,args,message){$('#modalBody').dataset.busy='1';setLoading(true);try{const {data,error}=await db.rpc(name,args);if(error)throw error;toast(message(data));$('#modalBody').dataset.busy='0';closeModal();await loadData();render()}catch(e){fail(e)}finally{$('#modalBody').dataset.busy='0';setLoading(false)}}

init().catch(e=>{setLoading(false);showLogin();$('#loginError').textContent=errorText(e);console.error(e)});
